services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    command: postgres -c shared_preload_libraries=timescaledb
    expose:
      - "5432"
    volumes:
      - store_monitoring_tsdb:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"

  stor:
    image: ghcr.io/p0lygun/store-monitoring/production:latest
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=timescaledb
      - DB_PORT=5432
    user: 0:0
    ports:
      - "8016:80"
    command: python -m stor

    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  store_monitoring_tsdb:
